app/settings/forms.py
from flask_wtf import Form
from wtforms import PasswordField, SelectField
from wtforms.validators import Length, EqualTo, DataRequired


class PreferencesForm(Form):
    language = SelectField('Default Syntax')


class ChangePasswordForm(Form):
    newpw = PasswordField('New Password',
                          validators=[
                              DataRequired(
                                  message="Both fields are required."),
                              Length(
                                  min=8,
                                  message="Password must be 8 characters."),
                              EqualTo(
                                  'confirmpw',
                                  message='Passwords do not match.')])
    confirmpw = PasswordField('Confirm New Password',
                              validators=[DataRequired()])

app/settings/views.py
from app import db
from app.forms import PreferencesForm, ChangePasswordForm
from app.models import Language
from app.util.helpers import populate_choice_field
from flask import flash, Blueprint, render_template
from flask_login import current_user, login_required

settings = Blueprint('settings', __name__)


@settings.route('/settings/', methods=['GET', 'POST'])
@login_required
def user_settings():
    """Route for users to customize their settings"""
    prefs_form = PreferencesForm()
    populate_choice_field(prefs_form)
    if prefs_form.validate_on_submit():
        current_user.default_language = Language.query.get(
            prefs_form.language.data
        )
        db.session.add(current_user)
        db.session.commit()
        flash('Your preferences have been saved!', 'success')

    if current_user.default_language:
        prefs_form.language.default = current_user.default_language_id
        prefs_form.process()

    return render_template('settings/settings.html', prefs_form=prefs_form)


@settings.route('/changepass/', methods=['GET', 'POST'])
@login_required
def change_password():
    """Route for logged in users to change password"""
    pw_form = ChangePasswordForm()
    if pw_form.validate_on_submit():
        # If new password is not equal to old
        if not current_user.validate_pass(pw_form.newpw.data):
            current_user.password = pw_form.newpw.data
            flash('Password successfuly changed!', 'info')
            db.session.add(current_user)
            db.session.commit()
        else:
            flash('Password must differ from the old.', 'danger')

    return render_template('settings/change_password.html', pw_form=pw_form)

app/templates/settings/change_password.html
{% extends 'base.html' %}
{% block content %}
<h2>Your settings</h2>
<h4>Change Password</h4>
<div class="row">
	<div class="col-sm-4">
		{% for error in pw_form.newpw.errors %}
		<div class="alert alert-danger text-center">
			{{ error }}
		</div>
		{% endfor %}
		<form action="{{ url_for('settings.change_password') }}" method='POST'>
			{{ pw_form.csrf_token }}
			<div class="form-group">
			{{ pw_form.newpw.label }}
			{{ pw_form.newpw(class="form-control") }}
			</div>
			<div class="form-group">
			{{ pw_form.confirmpw.label }}
			{{ pw_form.confirmpw(class="form-control") }}
			</div>
			<input value='Change Password' type='submit' class="btn btn-success">
		</form>
	</div>
</div>
{% endblock %}

app/templates/settings/settings.html
{% extends 'base.html' %}
{% block content %}
<h2>Your settings</h2>
<h4>Change Defaults</h4>
<div class="row">
	<div class="col-sm-4">
		<form action="{{ url_for('settings.user_settings') }}" method="POST">
			{{ prefs_form.csrf_token }}
			<div class="form-group">
				{{ prefs_form.language.label }}
				{{ prefs_form.language(class="form-control") }}
			</div>
			<input value="Save Preferences" type="submit" class="btn btn-success">
		</form>
		<a href="{{ url_for('settings.change_password') }}">Click here</a> to change you password.
	</div>
</div>
{% endblock %}