app/snippets/models.py
from app import app, db
import datetime
from hashids import Hashids


class Snippet(db.Model):
    __tablename__ = 'snippet'

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(80), default='Untitled')
    body = db.Column(db.Text(), nullable=False)
    private = db.Column(db.Boolean, default=False)
    hits = db.Column(db.Integer, default=0)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))
    language_id = db.Column(db.String, db.ForeignKey('language.id'))
    language = db.relationship('Language')
    date_added = db.Column(db.DateTime)

    parent_fork_id = db.Column(db.Integer, db.ForeignKey('snippet.id'))
    parent_fork = db.relationship('Snippet',
                                  backref=db.backref('forks', lazy='dynamic'),
                                  remote_side='Snippet.id')

    def __init__(self, body):
        self.body = body
        self.date_added = datetime.datetime.utcnow()

    def __repr__(self):
        return '{}: {}'.format(self.id, self.title)

    def get_uuid(self):
        hashid = Hashids(salt=app.config['HASHID_SALT'],
                         min_length=app.config['HASHID_LEN'])
        return hashid.encode(self.id)

    def is_private(self):
        return self.private


class Language(db.Model):
    __tablename__ = 'language'
    id = db.Column(db.String(32), primary_key=True)
    display_text = db.Column(db.String(64), nullable=False)
    extension = db.Column(db.String(32))

    def __init__(self, id, display_text, ext):
        self.id = id
        self.display_text = display_text
        self.extension = ext

    def __repr__(self):
        return self.display_text

app/snippets/forms.py
from flask_wtf import Form
from wtforms import TextAreaField, StringField, BooleanField
from wtforms import SelectField, SubmitField
from wtforms.validators import DataRequired


class SnippetForm(Form):
    title = StringField('Title')
    snippet = TextAreaField('snippet', validators=[DataRequired()])
    language = SelectField('language')
    private = BooleanField('Set Private?')


class DeleteForm(Form):
    delete = SubmitField('DELETE')

app/snippets/views.py
from app import app, db
from app.models import Language, Snippet
from app.forms import SnippetForm, DeleteForm
from app.util.errors import Unauthorized
from app.util.helpers import populate_choice_field
from app.util.getters import get_snippet_by_uuid

from datetime import date, timedelta
from flask import Blueprint, render_template, redirect
from flask import url_for, request, Response, make_response
from flask_login import login_required, current_user


snippets = Blueprint('snippets', __name__)


@snippets.route('/', methods=['GET', 'POST'])
def index():
    """Route allows users to create a new snippet"""
    snippet_form = SnippetForm()
    populate_choice_field(snippet_form)
    if snippet_form.validate_on_submit():
        s = Snippet(snippet_form.snippet.data)
        if snippet_form.title.data:
            s.title = snippet_form.title.data
        s.language = Language.query.get(snippet_form.language.data)
        if not current_user.is_anonymous():
            s.user = current_user
            s.private = snippet_form.private.data
        db.session.add(s)
        db.session.commit()
        return redirect(url_for('snippets.show_snippet',
                                snippet_uuid=s.get_uuid()))
    if current_user.is_authenticated() and current_user.default_language:
        snippet_form.language.default = current_user.default_language_id
        snippet_form.process()

    return render_template('snippets/compose.html', form=snippet_form)


@snippets.route('/<path:snippet_uuid>/')
def show_snippet(snippet_uuid):
    """Route shows a snippet given it's
    unique identifier - displayed in a read only
    codemirror textarea"""

    snippet = get_snippet_by_uuid(snippet_uuid)
    if snippet.is_private() and snippet.user != current_user:
        raise Unauthorized("This snippet is private.")
    snippet.hits = snippet.hits + 1
    db.session.add(snippet)
    db.session.commit()

    return render_template('snippets/view.html', snippet=snippet)


@snippets.route('/<path:snippet_uuid>/fork/')
@login_required
def fork_snippet(snippet_uuid):
    to_fork = get_snippet_by_uuid(snippet_uuid)
    if to_fork.is_private() and to_fork.user != current_user:
        raise Unauthorized("This snippet is private.")
    new_snippet = Snippet(to_fork.body)
    new_snippet.title = to_fork.title
    new_snippet.language = to_fork.language
    new_snippet.parent_fork = to_fork
    new_snippet.user = current_user
    db.session.add(new_snippet)
    db.session.commit()
    return redirect(url_for('snippets.show_snippet',
                            snippet_uuid=new_snippet.get_uuid()))


@snippets.route('/<path:snippet_uuid>/edit/', methods=['GET', 'POST'])
@login_required
def edit_snippet(snippet_uuid):
    """Route allows a user to modify a snippet if
    he or she is the owner"""

    snippet = get_snippet_by_uuid(snippet_uuid)

    if current_user != snippet.user:
        raise Unauthorized("You must be the creator or a snippet to edit it.")

    snippet_form = SnippetForm()
    populate_choice_field(snippet_form)

    if snippet_form.validate_on_submit():
        snippet.body = snippet_form.snippet.data
        if snippet_form.title.data:
            snippet.title = snippet_form.title.data
        snippet.language = Language.query.get(snippet_form.language.data)
        snippet.private = snippet_form.private.data
        db.session.add(snippet)
        db.session.commit()
        return redirect(url_for('snippets.show_snippet',
                                snippet_uuid=snippet.get_uuid()))

    snippet_form.title.default = snippet.title
    snippet_form.snippet.default = snippet.body
    snippet_form.language.default = snippet.language_id
    snippet_form.private.default = snippet.is_private()
    snippet_form.process()

    return render_template('snippets/compose.html',
                           form=snippet_form,
                           snippet=snippet)


@snippets.route('/<path:snippet_uuid>/r/')
def raw_snippet(snippet_uuid):
    """Route returns the raw text of a snippet
    in a blank page in the browser"""
    snippet = get_snippet_by_uuid(snippet_uuid)
    return Response(snippet.body, mimetype='text/plain')


@snippets.route('/<path:snippet_uuid>/d/')
def download_snippet(snippet_uuid):
    """Route returns a downloadable file containing
    the raw text of a snippet"""

    snippet = get_snippet_by_uuid(snippet_uuid)

    body = snippet.body
    ext = snippet.language.extension
    response = make_response(body)

    response.headers['Content-Disposition'] =\
        "attachment; filename={}{}".format(snippet_uuid, ext)
    return response


@snippets.route('/<path:snippet_uuid>/delete/', methods=['GET', 'POST'])
@login_required
def delete_snippet(snippet_uuid):
    """Route lets the owner of a snippet delete
    the snippet"""
    snippet = get_snippet_by_uuid(snippet_uuid)

    if current_user != snippet.user:
        message = "You are not authorized to edit this snippet."
        return render_template('errorpages/401.html', message=message), 401

    form = DeleteForm()

    if form.validate_on_submit():
        db.session.delete(snippet)
        db.session.commit()
        return redirect(url_for('user.snippets',
                                username=current_user.username))
    return render_template('snippets/delete.html', form=form, snippet=snippet)


@snippets.route('/ajaxdelete', methods=['POST'])
def ajax_delete():
    snip_uuid = request.form.get('snip_uuid', None)
    snippet = get_snippet_by_uuid(snip_uuid)
    if current_user == snippet.user:
        db.session.delete(snippet)
        db.session.commit()
        return Response('Delete Successful.', status=200) 
    return Response('Delete Unsuccessful.', status=401) 


@snippets.route('/popular/')
def popular_snippets():
    """Route shows popular snippets based on the
    timeframe in the querystring"""
    page = request.args.get('page', 1)
    t = request.args.get('t', 'week')

    # determine time frame based on querystring (t)
    if t == 'month':
        from_date = date.today() - timedelta(days=30)
    elif t == 'year':
        from_date = date.today() - timedelta(days=365)
    elif t == 'all':
        from_date = None
    else:
        from_date = date.today() - timedelta(weeks=1)

    snippets = Snippet.query.filter_by(private=False)
    if from_date:
        snippets = snippets.filter(Snippet.date_added > from_date)

    snippets = snippets.order_by(Snippet.hits.desc())\
                       .paginate(int(page),
                                 app.config['SNIPPETS_PER_PAGE'],
                                 False)
    return render_template('snippets/list.html',
                           snippets=snippets,
                           view='Popular')


@snippets.route('/recent/')
def recent_snippets():
    """Route shows recent public snippets in the
    last 5 days, ordered by date_added"""

    page = request.args.get('page', 1)

    # Get date 5 days ago to query back to
    from_date = date.today() - timedelta(days=10)
    snippets = Snippet.query.filter_by(private=False)\
                            .filter(Snippet.date_added > from_date)\
                            .order_by(Snippet.date_added.desc())
    snippets = snippets.paginate(int(page),
                                 app.config['SNIPPETS_PER_PAGE'],
                                 False)
    return render_template('snippets/list.html',
                           snippets=snippets,
                           view='Recent')

@snippets.route('/about/')
def about():
    """Route displays the static about page"""
    return render_template('public/about.html')

app/user/views.py
from app import app, db, login_manager
from app.forms import LoginForm, RequestResetForm
from app.forms import PasswordResetForm, SignupForm
from app.util.email import generate_token, decode_token, send_email
from app.util.getters import get_user_by_username
from app.util.decorators import anonymous_required
from app.models import Snippet, User
from datetime import datetime
from flask import Blueprint, request, render_template, redirect, url_for, flash
from flask_login import current_user, login_required, logout_user, login_user
from itsdangerous import SignatureExpired, BadSignature

user = Blueprint('user', __name__)


@login_manager.user_loader
def load_user(id):
    return User.query.get(int(id))


@user.route('/u/<path:username>/')
def snippets(username):
    """Route returns snippets and their info for
    snippets created by specified user"""
    user = get_user_by_username(username)

    # set order_by variables based on querystring
    direction = request.args.get('dir', 'asc')
    field = request.args.get('sort', 'date')

    # set page to 1 in case it wasn't specified
    page = 1
    if request.args.get('page'):
        page = request.args.get('page')

    # set base query for user's snippets
    snip_query = Snippet.query.filter_by(user=user)
    if current_user != user:
        snip_query = snip_query.filter_by(private=False)

    # ensure direction and field are valid
    if field not in ('date', 'title', 'views', 'syntax'):
        field = 'title'
    else:
        if field == 'date':
            field = 'date_added'
        if field == 'views':
            field = 'hits'
        if field == 'syntax':
            field = 'language_id'
    if direction not in ('desc', 'asc'):
        direction = 'asc'

    sort_by = '{} {}'.format(field, direction)
    snip_query = snip_query.order_by(sort_by)

    snippets = snip_query.paginate(int(page),
                                   app.config['SNIPPETS_PER_PAGE'],
                                   False)
    return render_template('user/index.html', user=user, snippets=snippets)


@user.route('/login/', methods=['POST', 'GET'])
@anonymous_required
def login():
    """Log in users if they are registered and confirmed,
    provided they supply the correct password"""
    login_form = LoginForm()
    next_url = request.args.get('next', url_for('snippets.index'))

    if login_form.validate_on_submit():
        username = login_form.username.data
        password = login_form.password.data
        registered_user = User.query.filter_by(username=username).first()

        if not registered_user or not registered_user.validate_pass(password):
            flash('Incorrect username or password', 'danger')
        elif not registered_user.is_confirmed():
            flash('You must confirm your email before logging in.', 'danger')
        else:
            login_user(registered_user)
            return redirect(next_url)
        return redirect(url_for('user.login'))

    return render_template('user/login.html', form=login_form)


@user.route('/logout/')
@login_required
def logout():
    """Route logs a user out of the session"""
    logout_user()
    return redirect(url_for('snippets.index'))


@user.route('/signup/', methods=['POST', 'GET'])
@anonymous_required
def signup():
    """Route for letting a user sign up"""
    signup_form = SignupForm()
    if signup_form.validate_on_submit():
        email = signup_form.email.data
        u = User(signup_form.username.data, email,
                 signup_form.password.data)
        db.session.add(u)
        db.session.commit()
        confirm_token = generate_token(email)
        email_body = 'Welcome to snip.space! <a href="{}">Click here</a> to confirm your email!'\
                     .format(url_for('user.confirm_email',
                                     confirm_token=confirm_token,
                                     _external=True))

        send_email.delay(email, 'Confirm snip.space Email Address', email_body)
        flash('Check your email for a confirmation link!', 'info')
        return redirect(url_for('user.login'))
    return render_template('user/signup.html', form=signup_form)


@user.route('/confirm/<path:confirm_token>/')
def confirm_email(confirm_token):
    """Route takes a token that is sent to users to confirm
    an email address. If email address exists in the database,
    the user's confirmed status is set to true."""
    try:
        email = decode_token(confirm_token)
    except SignatureExpired:
        return "This token has expired."
    except BadSignature:
        return "Invalid token."

    user = User.query.filter(User.email == email).one()

    if user.is_confirmed():
        return "You have already confirmed your email address."
    user.confirmed = True
    user.confirmed_date = datetime.utcnow()
    db.session.add(user)
    db.session.commit()
    flash('Your email has been confirmed! You man now log in.', 'success')
    return redirect(url_for('user.login'))


@user.route('/request-reset/', methods=['GET', 'POST'])
@anonymous_required
def request_reset():
    form = RequestResetForm()

    if form.validate_on_submit():
        user = None
        try:
            user = User.query.filter(User.email == form.email.data).one()
        except:
            pass
        if user:
            email = user.email
            reset_token = generate_token(email)
            email_body = '<a href="{}">Click here</a> to reset your snip.space password.'\
                         .format(url_for('user.reset_password',
                                         reset_token=reset_token,
                                         _external=True))
            send_email.delay(email,
                             'Password Reset for snip.space',
                             email_body)
            message = """A link to reset your password has been
                         sent to the email address <strong>{}</strong>.
                         Check your email, and follow the provided link
                         to continue.""".format(email)
            return render_template('message.html',
                                   title="Reset Email Sent",
                                   message=message)
        else:
            flash('Email not found in our records.', 'danger')
            return redirect(url_for('user.request_reset'))

    return render_template('user/request_reset.html', form=form)


@user.route('/reset/<path:reset_token>/', methods=['GET', 'POST'])
@anonymous_required
def reset_password(reset_token):
    try:
        email = decode_token(reset_token)
    except SignatureExpired:
        return "This token has expired."
    except BadSignature:
        return "Invalid token."

    form = PasswordResetForm()

    if form.validate_on_submit():
        user = User.query.filter(User.email == email).one()
        if email != form.email.data:
            flash('Email not valid', 'danger')
        else:
            user.password = form.password.data
            db.session.add(user)
            db.session.commit()
            flash('Your password has been reset. Log in!', 'success')
            return redirect(url_for('user.login'))
    return render_template('user/reset_password.html',
                           form=form,
                           reset_token=reset_token)

app/templates/snippets/compose.html
{% extends 'base.html' %}
{% block content %}
{% if snippet %}
<h3>Edit snippet {{ snippet.get_uuid() }}: <em>{{ snippet.title }}</em></h3>
<form method="POST" action="{{ url_for('snippets.edit_snippet', snippet_uuid=snippet.get_uuid()) }}">
{% else %}
<form method="POST" action="/">
{% endif %}
	{{ form.csrf_token }}
	<div class="row">
		<div class="col-sm-3">
		{{ form.language(class="form-control") }}
		</div>
		<div class="form-group col-sm-9">
		{{ form.title(placeholder="Enter title here...",
					  class="form-control") }}
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-12">
		{{ form.snippet(id="snippet_editable",
						class="snippet-textarea",
						rows=20 ) }}
		</div>
	</div>
	<div class="checkbox">
		{% if current_user.is_authenticated() %}
		<label>
		{{ form.private }} Set Private?
		</label>
		{% else %}
		<label>
		{{ form.private(disabled="true") }} Set Private?
		</label> (<a href="{{ url_for('user.login') }}">Login</a> or <a href="{{ url_for('user.signup') }}">Signup</a>)
		{% endif %}
	</div>
	{% if snippet %}
	<div class="row">
		<div class="col-sm-8">
			<input type="submit" value="Save Snippet"
					class="btn btn-success btn-block" />
		</div>
		<div class="col-sm-4">
			<a href="/" class="btn btn-danger btn-block" />
				Cancel
			</a>
		</div>
	</div>
	{% else %}
	<input type="submit" value="Submit"
		   class="form-control btn btn-success btn-block" />
	{% endif %}
	</div>
</form>
<script>
window.onload = function () {
  
    var editableCodeMirror = CodeMirror.fromTextArea(document.getElementById('snippet_editable'), {
        mode: "javascript",
        theme: "default",
        lineNumbers: true
    });
    editableCodeMirror.setSize('100%', 400); 
};
</script>
{% endblock %}

app/templates/snippets/delete.html
{% extends 'base.html' %}
{% block content %}
<div class="text-center">
<h3>Are you sure you want to delete <strong>{{ snippet.get_uuid() }}</strong>:</h3>
<h4><em>{{ snippet.title }}</em></h4>
<form action="{{ url_for('snippets.delete_snippet', snippet_uuid=snippet.get_uuid()) }}" method="POST">
	{{ form.csrf_token }}
	{{ form.delete(class="btn btn-danger") }}
	<a class="btn btn-warning" href="{{ url_for('user.snippets', username=current_user.username) }}">No, abort.</a>
</form>
</div>
{% endblock %}

app/templates/snippets/list.html
{% extends 'base.html' %}
{% import 'macros/items.html' as items  with context %}
{% block content %}
<h2 class="pull-left">{{ view }} Snippets</h2>
{% if view == 'Popular' %}
<nav class="timespan-nav pull-right">
	{{ items.timelink('week', 'This Week') }} | 
	{{ items.timelink('month', 'This Month') }} | 
	{{ items.timelink('all', 'All Time') }}
</nav>
{% endif %}
<table class="table table-striped table-condensed">
	<thead>
		<th class="col-sm-6">Title</th>
		<th>User</th>
		<th>Date Added</th>
		<th>Syntax</th>
		<th>Views</th>
	</thead>
	<tbody>
		{% for snippet in snippets.items%}
		<tr>
			<td><a href="{{ url_for('snippets.show_snippet', snippet_uuid=snippet.get_uuid()) }}" >{{ snippet.title }}</a></td>
			<td>
				{%- if snippet.user -%}
				<a href="{{ url_for('user.snippets', username=snippet.user.username) }}">{{ snippet.user.username }}</a>
				{%- else -%}
				Anonymous
				{%- endif -%}
			</td>
			<td>{{ snippet.date_added.strftime('%b %d, %Y') }}</td>
			<td>{{ snippet.language }}</td>
			<td>{{ snippet.hits }}</td>
		</tr>
		{% endfor %}
	</tbody>
</table>
{% if snippets.items %}
{{ items.paginate(snippets) }}
{% endif %}
{% endblock %}

app/templates/snippets/view.html
{% extends 'base.html' %}
{% block css %}
<link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css">
{% endblock %}
{% block content %}

	<div class="row">
		<div class="col-sm-12">
			<h3>
				{% if snippet.is_private() %}
				<i class="fa fa-lock"></i> 
				{% else %}
				<i class="fa fa-unlock"></i> 
				{% endif %}
				{{ snippet.title }}
			</h3>
		</div>
		<div class="snippet-info col-sm-7">
			<small>Created by: 
				{% if snippet.user %}
					<a href="{{url_for('user.snippets', username=snippet.user) }}">{{ snippet.user }}</a> 
					{% else %}Anonymous{% endif %} | Views: {{ snippet.hits }} | Created on: {{ snippet.date_added.strftime('%b %d, %Y') }} | Syntax: {{ snippet.language.display_text }} | Forked: {{ snippet.forks.count() }}</small>
		</div>
		<div class="snippet-options col-md-5 pull-right">
			<a href="fork">Fork It!</a> | <a href="r">Raw Text</a> | <a href="d">Download</a> |  <a href="/report/{{ snippet.id }}">Report</a> 
		</div>
	</div>
	<div class="row">
		<div class="form-group col-sm-12">
			<textarea disabled class="snippet-textarea" id="snippet_readonly" rows=20>{{ snippet.body }}</textarea>
		</div>
		<div class="col-sm-8">
			<a href="/" class="new-snippet-btn btn btn-default"><span class="glyphicon glyphicon-plus"></span> New Snippet</a>
			{% if current_user == snippet.user %}
			<a href="{{ url_for('snippets.edit_snippet', snippet_uuid=snippet.get_uuid()) }}" class="btn btn-primary">
				<span class="fa fa-pencil"></span> Edit
			</a>
			<a href="{{ url_for('snippets.delete_snippet', snippet_uuid=snippet.get_uuid()) }}" class="btn btn-danger">
				<span class="fa fa-trash"></span> Delete
			</a>
			{% endif %}
		</div>
		<div class="col-sm-4 options-container">
			<div class="input-group">
				<span class="input-group-addon">Share:</span>
				<input disabled id="copy-me" class="form-control" type="text" value="http://snip.space/{{ snippet.get_uuid() }}" />
				<span class="input-group-btn">
					<button class="btn btn-primary" type="button" data-clipboard-target="copy-me" id="copy-button">Copy</button>
				</span>
			</div>
		</div>
	</div>
	{% block scripts %}
	{{ super() }}
	<script src="https://code.jquery.com/jquery-1.11.3.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
	<script src="{{ url_for('static', filename='js/ZeroClipboard.min.js') }}"></script>
	<script src="{{ url_for('static', filename='components/codemirror/addon/mode/loadmode.js') }}"></script>
	<script src="{{ url_for('static', filename='components/codemirror/mode/meta.js') }}"></script>
	{% if snippet.language.id == 'htmlmixed' %}
	{% endif %}
	{% endblock %}
	<script>
	window.onload = function () {
		CodeMirror.modeURL = "/static/components/codemirror/mode/%N/%N.js";
		ZeroClipboard.config( { swfPath: '{{ url_for('static', filename="js/ZeroClipboard.swf") }}'} );
		var client = new ZeroClipboard(document.getElementById('copy-button'));

		client.on( "ready", function( readyEvent ){
			client.on( "aftercopy", function( event ){
				toastr.success('Copied to Clipboard!');
			});
		});

	    var editableCodeMirror = CodeMirror.fromTextArea(document.getElementById('snippet_readonly'), {
			path: "static/components/codemirror",
			mode: "{{ snippet.language.id }}",
	        theme: "default",
	        lineNumbers: true,
	        readOnly: true
	    });
	    editableCodeMirror.setSize('100%', 400); 
	    editableCodeMirror.setOption('mode','{{ snippet.language.id }}'); 
	    CodeMirror.autoLoadMode(editableCodeMirror, '{{ snippet.language.id }}'); 
	};
	</script>
{% endblock %}